name: execute

on:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  execute:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute
        run: |
          python -m exercise_report_slack.main
