name: pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: DUMMY_TOKEN
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint with flake8
        run: flake8
      - name: Use Node.js 14.4
        uses: actions/setup-node@v1
        with:
          node-version: 14.4
      - run: npm install pyright
      - name: Lint with pyright
        run: |
          npm install pyright
          pyright
